[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [".env"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  BRANCH = "main"

[context.production]
  publish = "dist"
  command = "npm run build"
  environment = { BRANCH = "main" }

[context.deploy-preview]
  ignore = "exit 0"

[context.branch-deploy]
  ignore = "exit 0"

[context.main]
  base = "/"
  publish = "dist"
  command = "npm run build"
  environment = { BRANCH = "main" }